### PR TITLE
classpaths?

### PR DESCRIPTION
**Pull request by blorente**
Repro steps below

### CODE REVIEW

**Comment by dotordogh** [comment]
To repro:
First you need to check out `1592575c54ccbc8b0b6869e10ed698cf4b09b39c` after fetching Borja’s fork (https://github.com/blorente/pants). Then you want to run `./pants binary src/scala/org/pantsbuild/zinc/bootstrapper:runner` to create the binary in `dist` and also run a publish by running `./pants publish  --publish-jar-local=~/.m2/repository --publish-jar-local-snapshot --no-publish-jar-dryrun src/scala/org/pantsbuild/zinc/bootstrapper:runner` to publish the binary locally. Then you need to checkout `c4d7e010dbb73c38d63c4b53e64b95f7f9eab668` and run `./pants clean-all run testprojects/src/scala/org/pantsbuild/testproject/simple::` to repro the failure and to get the java compile commands to run separately. It will look something like 
```
18:27:02 00:05         [cache].
                     Using cached artifacts for 1 target.Invoking compilation (this is the command line we have been experimenting with):  /Library/Java/JavaVirtualMachines/jdk1.8.0_111.jdk/Contents/Home/bin/java -cp .pants.d/bootstrap/bootstrap-jvm-tools/tool_cache/shaded_jars/org.pantsbuild.zinc.bootstrapper.Main-1d7463ad185d32a7d1585e7f3ee734f74f8a1043-ShadedToolFingerprintStrategy_e2ba67beff2a.jar org.pantsbuild.zinc.bootstrapper.Main /tmp/bdd.jar /Users/bescobar/workspace/otherpants/.pants.d/bootstrap/bootstrap-jvm-tools/tool_cache/shaded_jars/no.such.main.Main-a6da447d452f0635bafcd343f20afa7f91023dcf-ShadedToolFingerprintStrategy_e2ba67beff2a.jar /Users/bescobar/workspace/otherpants/.pants.d/ivy/jars/org.scala-sbt/compiler-bridge_2.11/jars/compiler-bridge_2.11-1.0.3-sources.jar /Users/bescobar/.ivy2/pants/org.scala-lang/scala-compiler/jars/scala-compiler-2.11.12.jar /Users/bescobar/.ivy2/pants/org.scala-lang/scala-library/jars/scala-library-2.11.12.jar
``` 

Then if you run that command on the command line with the `dist/runner.jar` instead of `.pants.d/bootstrap/bootstrap-jvm-tools/tool_cache/shaded_jars/org.pantsbuild.zinc.bootstrapper.Main-1d7463ad185d32a7d1585e7f3ee734f74f8a1043-ShadedToolFingerprintStrategy_e2ba67beff2a.jar `, it should pass :smile:

**Comment by stuhood** [comment]
Thanks.

One additional bit that is necessary is to publish a compiler snapshot while on 1592575c54ccbc8b0b6869e10ed698cf4b09b39c.... that looks like `./pants publish --publish-jar-local=~/.m2/repository --publish-jar-local-snapshot --no-publish-jar-dryrun src/scala/org/pantsbuild/zinc/compiler/::`. (sidenote: that also publishes the `bootstrapper`, which implies that the `compiler` depends on the `boostrapper`... it probably shouldn't.)

**Comment by stuhood** [comment]
After fixing that issue, I see:
```
Invoking compilation (this is the command line we have been experimenting with):  /Library/Java/JavaVirtualMachines/jdk1.8.0_111.jdk/Contents/Home/bin/java -cp .pants.d/bootstrap/bootstrap-jvm-tools/tool_cache/shaded_jars/org.pantsbuild.zinc.bootstrapper.Main-1d7463ad185d32a7d1585e7f3ee734f74f8a1043-ShadedToolFingerprintStrategy_e2ba67beff2a.jar org.pantsbuild.zinc.bootstrapper.Main /tmp/bdd.jar /Users/stuhood/src/pants/.pants.d/bootstrap/bootstrap-jvm-tools/tool_cache/shaded_jars/no.such.main.Main-a6da447d452f0635bafcd343f20afa7f91023dcf-ShadedToolFingerprintStrategy_e2ba67beff2a.jar /Users/stuhood/src/pants/.pants.d/ivy/jars/org.scala-sbt/compiler-bridge_2.11/jars/compiler-bridge_2.11-1.0.3-sources.jar /Users/bescobar/.ivy2/pants/org.scala-lang/scala-compiler/jars/scala-compiler-2.11.12.jar /Users/bescobar/.ivy2/pants/org.scala-lang/scala-library/jars/scala-library-2.11.12.jar
Exception in thread "main" sbt.internal.inc.InvalidScalaInstance: Scala instance doesn't exist or is invalid:
    version unknown, library jar: /Users/bescobar/.ivy2/pants/org.scala-lang/scala-library/jars/scala-library-2.11.12.jar, compiler jar: /Users/bescobar/.ivy2/pants/org.scala-lang/scala-compiler/jars/scala-compiler-2.11.12.jar, other jars: /Users/bescobar/.ivy2/pants/org.scala-lang/scala-reflect/jars/scala-reflect-2.11.12.jar, /Users/bescobar/workspace/otherpants/.pants.d/ivy/jars/org.scala-sbt/util-interface/jars/util-interface-1.0.3.jar
	at sbt.internal.inc.ScalaInstance$.slowActualVersion(ScalaInstance.scala:240)
	at sbt.internal.inc.ScalaInstance$.sbt$internal$inc$ScalaInstance$$actualVersion(ScalaInstance.scala:225)
	at sbt.internal.inc.ScalaInstance$$anonfun$actualVersion$1.apply(ScalaInstance.scala:88)
	at sbt.internal.inc.ScalaInstance$$anonfun$actualVersion$1.apply(ScalaInstance.scala:86)
	at scala.Option.getOrElse(Option.scala:121)
	at sbt.internal.inc.ScalaInstance.actualVersion$lzycompute(ScalaInstance.scala:86)
	at sbt.internal.inc.ScalaInstance.actualVersion(ScalaInstance.scala:85)
	at sbt.internal.inc.AnalyzingCompiler$$anonfun$compileSources$1$$anonfun$apply$2.apply(AnalyzingCompiler.scala:342)
	at sbt.internal.inc.AnalyzingCompiler$$anonfun$compileSources$1$$anonfun$apply$2.apply(AnalyzingCompiler.scala:341)
	at sbt.io.IO$.withTemporaryDirectory(IO.scala:376)
	at sbt.io.IO$.withTemporaryDirectory(IO.scala:383)
	at sbt.internal.inc.AnalyzingCompiler$$anonfun$compileSources$1.apply(AnalyzingCompiler.scala:341)
	at sbt.internal.inc.AnalyzingCompiler$$anonfun$compileSources$1.apply(AnalyzingCompiler.scala:335)
	at sbt.io.IO$.withTemporaryDirectory(IO.scala:376)
	at sbt.io.IO$.withTemporaryDirectory(IO.scala:383)
	at sbt.internal.inc.AnalyzingCompiler$.compileSources(AnalyzingCompiler.scala:335)
	at org.pantsbuild.zinc.bootstrapper.BootstrapperUtils$.compile$1(BootstrapperUtils.scala:56)
	at org.pantsbuild.zinc.bootstrapper.BootstrapperUtils$.compilerInterface(BootstrapperUtils.scala:69)
	at org.pantsbuild.zinc.bootstrapper.Main$.main(Main.scala:51)
	at org.pantsbuild.zinc.bootstrapper.Main.main(Main.scala)
Caused by: java.lang.ClassNotFoundException: scala.tools.nsc.Properties
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at sbt.internal.inc.ScalaInstance$.slowActualVersion(ScalaInstance.scala:233)
	... 19 more
```

... which is caused by the hardcoded paths in the PR. But we don't raise an exception for the failed bootstrap, which is because https://github.com/blorente/pants/pull/1/files#diff-3ab9f33a703cf0df2ff4fbf7a626b4d1R198 doesn't check the return code of the process.

**Comment by stuhood** [comment]
After fixing the hardcoded paths and not checking the return code, the bootstrap process fails with:
```
Exception in thread "main" java.lang.NoClassDefFoundError: scala/reflect/internal/Reporter
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.getDeclaredMethods0(Native Method)
	at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
	at java.lang.Class.privateGetMethodRecursive(Class.java:3048)
	at java.lang.Class.getMethod0(Class.java:3018)
	at java.lang.Class.getMethod(Class.java:1784)
	at sbt.internal.inc.RawCompiler.getReporter$1(RawCompiler.scala:49)
	at sbt.internal.inc.RawCompiler.apply(RawCompiler.scala:71)
	at sbt.internal.inc.AnalyzingCompiler$$anonfun$compileSources$1$$anonfun$apply$2$$anonfun$apply$1.apply$mcV$sp(AnalyzingCompiler.scala:350)
	at sbt.internal.inc.AnalyzingCompiler$.sbt$internal$inc$AnalyzingCompiler$$handleCompilationError$1(AnalyzingCompiler.scala:327)
	at sbt.internal.inc.AnalyzingCompiler$$anonfun$compileSources$1$$anonfun$apply$2.apply(AnalyzingCompiler.scala:346)
	at sbt.internal.inc.AnalyzingCompiler$$anonfun$compileSources$1$$anonfun$apply$2.apply(AnalyzingCompiler.scala:341)
	at sbt.io.IO$.withTemporaryDirectory(IO.scala:376)
	at sbt.io.IO$.withTemporaryDirectory(IO.scala:383)
	at sbt.internal.inc.AnalyzingCompiler$$anonfun$compileSources$1.apply(AnalyzingCompiler.scala:341)
	at sbt.internal.inc.AnalyzingCompiler$$anonfun$compileSources$1.apply(AnalyzingCompiler.scala:335)
	at sbt.io.IO$.withTemporaryDirectory(IO.scala:376)
	at sbt.io.IO$.withTemporaryDirectory(IO.scala:383)
	at sbt.internal.inc.AnalyzingCompiler$.compileSources(AnalyzingCompiler.scala:335)
	at org.pantsbuild.zinc.bootstrapper.BootstrapperUtils$.compile$1(BootstrapperUtils.scala:56)
	at org.pantsbuild.zinc.bootstrapper.BootstrapperUtils$.compilerInterface(BootstrapperUtils.scala:69)
	at org.pantsbuild.zinc.bootstrapper.Main$.main(Main.scala:51)
	at org.pantsbuild.zinc.bootstrapper.Main.main(Main.scala)
Caused by: java.lang.ClassNotFoundException: scala.reflect.internal.Reporter
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 55 more
```

Which either means that:
1. the bootstrap binary has an undeclared dependency on `org.scala-lang/scala-reflect/jars/scala-reflect-2.11.12.jar`
2. Creating a `RawCompiler` for a particular scala version requires a `scala-reflect` jar that corresponds to the `scala-compiler` that is in use.

**Comment by stuhood** [comment]
I see the same exception from https://github.com/blorente/pants/pull/1#issuecomment-418491219 for both `dist/runner.jar` and `.pants.d/bootstrap/bootstrap-jvm-tools/tool_cache/shaded_jars/org.pantsbuild.zinc.bootstrapper.Main-1d7463ad185d32a7d1585e7f3ee734f74f8a1043-ShadedToolFingerprintStrategy_e2ba67beff2a.jar`.

...Which I think leans toward item 2 in that comment being the issue: ie it's not your process that needs scala-reflect: it's the compiler we're invoking. If you look at the zinc code in play, it's attempting to invoke the compiler you've given it in order to compile the bridge jar: https://github.com/sbt/zinc/blob/develop/internal/zinc-compile-core/src/main/scala/sbt/internal/inc/RawCompiler.scala#L46

So, I think that the bootstrapper needs more CLI arguments in order to receive scala-reflect so that it can use it during that compile.

**Comment by stuhood** [comment]
One more comment here: I'd strongly recommend against ever using `-SNAPSHOT` suffixed jars, because they can cause lots of caching issues. If I had to guess, the reason you see a difference between `dist/runner` and the shaded jar is because you published a different version of `0.0.1-SNAPSHOT` at some point, re-published, and expected to see the new code. But ivy just kept on fetching the previous copy of `0.0.1-SNAPSHOT` that it had cached.

Prefer `--named-snapshot='my-named-snapshot-1'` (with an incrementing version number that you bump on both the publish/consume side) for consuming snapshots for development.

**Pull request closed without merging**
